### PR TITLE
Create a Github Pages [english] Documentation

### PR DESCRIPTION
**Pull request by darkterminal**
Demo here: https://darkterminal.github.io/webman/ english version of Webman Documentation and this is't completed yet.

### CODE REVIEW

**Comment by walkor** [comment]
Hi @darkterminal 
Thank you for your pr. But this is the main repository of webman, not a document repository. I will try to build a multilingual webman site repository later, and then you can submit documents to it. Thanks alot.

**Comment by darkterminal** [comment]
@walkor so I will waiting... then give me signal for that event please. Thanks! :smile:

**Comment by walkor** [comment]
Hi @darkterminal 
Please submit docs to https://github.com/webman-php/webman-manual
🤝

**Comment by walkor** [comment]
English docs should submit to https://github.com/webman-php/webman-manual/tree/master/resource/doc/en

**Comment by darkterminal** [comment]
Ok... thanks mate! :smile: I will close this and see you...

**Pull request closed without merging**
